app:
  name: 'go-clean-template'
  version: '1.0.0'
  resources_dir: './config/resources'

http:
  port: '8080'
  metric_port: '8081'

logger:
  level: 'debug'
  log_dir: './app-log'
  use_std_and_file: true
  add_low_priority_level_to_cmd: true
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 2

rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'